#--------------------------------------------------------------------------#
#                          ${PROJECT_NAME}                                #
#--------------------------------------------------------------------------#
version: "3.8"

networks:
    laravel-network:
        driver: bridge

volumes:
    mariadb_data:

services:
    db:
        image: bitnami/mariadb:latest
        container_name: ${PROJECT_NAME}_db
        restart: always
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
            MARIADB_USER: bn_myapp
            MARIADB_DATABASE: bitnami_myapp
        networks:
            - laravel-network
        volumes:
            - mariadb_data:/bitnami/mariadb

    app:
        image: bitnami/laravel:latest
        container_name: ${PROJECT_NAME}_app
        restart: always
        ports:
            - "8000:8000"
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_USERNAME: bn_myapp
            DB_DATABASE: bitnami_myapp
        networks:
            - laravel-network
        volumes:
            - ./:/app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${PROJECT_NAME}_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "81:80"
        networks:
            - laravel-network
